# action.yml
name: 'AWS Elastic Beanstalk cli'

author: Jose bravo

description: 'Provides eb cli commands and a way to move to another folder'

branding:
  icon: 'terminal'  
  color: 'white'
  
inputs:
  folder:
    description: 'From where to run the eb command'

  command:  # id of input
    description: 'eb <command>'
    required: true
    default: 'deploy'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.folder }}
